use_frameworks!

platform :osx, '10.11'

target 'Cocoalytics' do

    pod 'GetLaid', :path=> '../../Frameworks/GetLaid'
    pod 'UIObserver', :path=> '../../Frameworks/UIObserver'
    pod 'UIToolz', :path=> '../../Frameworks/UIToolz'
    pod 'FoundationToolz', :path=> '../../Frameworks/FoundationToolz'
    pod 'SwiftObserver', :path=> '../../Frameworks/SwiftObserver'
    pod 'SwiftyToolz', :path=> '../../Frameworks/SwiftyToolz'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.11'
        end
    end
end
